import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Listlify",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: "600",
  subsets: ["latin"],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={poppins.className}
      >
        {children}
      </body>
    </html>
  );
}
