import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Listlify",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: "600",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} min-h-screen bg-gradient-to-br from-blue-200 via-blue-100 to-sky-100`}
      >
        {children}
      </body>
    </html>
  );
}
